name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests with coverage
        run: |
          cd src
          coverage run -m unittest discover
          coverage report

      - name: Upload coverage to GitHub Actions
        run: |
          cd src
          coverage xml
          curl -s https://codecov.io/bash | bash
