name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: '0 0 1 * *' # Run at 00:00 on the first day of every month
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        id: youtube-cards
        with:
          channel_id: UCHadELD-gro_9fm47EJrcUw
      - if: ${{ steps.youtube-cards.outputs.committed == 'false' }}
        run: echo "No new youtube video in the past month!"; exit 1;
